namespace EF_MultipleDbContext.Migrations
{
    using System.Data.Entity.Migrations;

    // Auto-Generated by :

    // enable-migrations -ContextTypeName:EF_MultipleDbContext.MyStudentContext

    internal sealed class Configuration : DbMigrationsConfiguration<Database.MyStudentContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(Database.MyStudentContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
        }
    }

    // After this - add first init config migration :

    // add-migration -configuration EF_MultipleDbContext.Migrations.Configuration Initial
}
